export const CURRENCIES = [
  { value: "MAD", label: "MAD — Moroccan Dirham" },
  { value: "USD", label: "USD — US Dollar" },
  { value: "EUR", label: "EUR — Euro" },
  { value: "GBP", label: "GBP — British Pound" },
  { value: "AED", label: "AED — UAE Dirham" },
  { value: "SAR", label: "SAR — Saudi Riyal" },
  { value: "QAR", label: "QAR — Qatari Riyal" },
  { value: "KWD", label: "KWD — Kuwaiti Dinar" },
  { value: "TND", label: "TND — Tunisian Dinar" },
  { value: "DZD", label: "DZD — Algerian Dinar" },
  { value: "EGP", label: "EGP — Egyptian Pound" },
  { value: "XOF", label: "XOF — West African CFA Franc" },
  { value: "XAF", label: "XAF — Central African CFA Franc" },
  { value: "NGN", label: "NGN — Nigerian Naira" },
  { value: "ZAR", label: "ZAR — South African Rand" },
  { value: "TRY", label: "TRY — Turkish Lira" },
  { value: "CHF", label: "CHF — Swiss Franc" },
  { value: "CAD", label: "CAD — Canadian Dollar" },
  { value: "AUD", label: "AUD — Australian Dollar" },
  { value: "JPY", label: "JPY — Japanese Yen" },
  { value: "CNY", label: "CNY — Chinese Yuan" },
  { value: "INR", label: "INR — Indian Rupee" },
  { value: "BRL", label: "BRL — Brazilian Real" },
  { value: "MXN", label: "MXN — Mexican Peso" },
  { value: "SEK", label: "SEK — Swedish Krona" },
  { value: "NOK", label: "NOK — Norwegian Krone" },
  { value: "PLN", label: "PLN — Polish Zloty" },
  { value: "RUB", label: "RUB — Russian Ruble" },
] as const

export type CurrencyCode = (typeof CURRENCIES)[number]["value"]
